version: '3'
services:
    postgres:
        image: postgres:10
        container_name: postgres
        ports:
          - "5432:5432"
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_DB=terawhars
            - POSTGRES_USER=terawhars
            - POSTGRES_PASSWORD=terawhars
            - POSTGRES_PORT=5432
        volumes:
            - $PWD/input_files/import-postgres.sql:/docker-entrypoint-initdb.d/import-postgres.sql
            - $PWD/output_files/postgres_data:/var/lib/postgresql/data
    adminer:
        image: adminer
        container_name: adminer
        depends_on:
            - postgres
        ports:
            - 8081:8080
    wildfly:
        image: terawhars
        container_name: wildfly
        build: .
        ports:
            - "8080:8080"
            - "9990:9990"
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=terawhars
            - DB_USER=terawhars
            - DB_PASS=terawhars
            - DS_NAME=TeraWHARSDS
            - JNDI_NAME=java:jboss/datasources/TeraWHARSDS
        depends_on:
            - postgres
        volumes:
            - $PWD/output_files/logs:/opt/jboss/wildfly/standalone/log
            - $PWD/output_files/terawharsdata:/opt/jboss/wildfly/terawharsdata
            - jboss-conf:/opt/jboss/wildfly/standalone/configuration
    keycloak:
        image: jboss/keycloak:6.0.1.Final
        container_name: keycloak
        ports:
            - "8083:8080"
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=postgres
            - DB_DATABASE=terawhars
            - DB_USER=terawhars
            - DB_PASSWORD=terawhars
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        depends_on:
            - postgres
    weblogs:
        image: opencell/alpine-tailon
        container_name: tailon
        depends_on:
            - wildfly
        ports:
            - 8082:8080
        volumes:
            - $PWD/output_files/logs:/logs/
volumes:
    jboss-conf: {}